### ISSUE TITLE
Sintesis 

### ISSUE THREAD

**Issue by DuilioAquino10** [SistemasTecTlaxiaco/actividad-3-sintesis-DuilioAquino10#2]
[Sintesis.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-DuilioAquino10/files/9472275/Sintesis.pdf)

**Comment by Rmz-Rigo** [comment]
CALIFICACION:18/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
